
const ActionTypes = {
	FETCH_STORY_STARTED: 'FETCH_STORY_STARTED',
	FETCH_COMMENTS_STARTED: 'FETCH_COMMENTS_STARTED',
	FETCH_STORY_DONE: 'FETCH_STORY_DONE',
	ADD_COMMENTS: 'ADD_COMMENTS',
	FETCH_KID_COMMENTS_DONE: 'FETCH_KID_COMMENTS_DONE',
};

export default ActionTypes;
